stages:
    - deploy

workflow:
    rules:
        - if: $CI_COMMIT_BRANCH == "main"

heroku_deploy:
    stage: deploy
    script:
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY
